config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root :to => 'homes#index' #rootにアクセスするとhomesコントローラーのindexアクションを実行
get '/books' => 'books#list' #/booksにアクセスするとbooksコントローラーのlistアクションを実行
get '/books/:id' => 'books#show', as: 'book'
get '/books/:id/edit' => 'books#edit', as: 'edit_book'
patch '/books/:id' => 'books#update', as: 'update_book'
post 'books' => 'books#create'
delete '/books/:id' => 'books#destroy', as: 'destroy_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord

  validates :title, presence: true
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def list
    @books = List.all
    @list = List.new
  end

  def create
    list = List.new(list_params)
    list.save
    redirect_to '/books'
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to book_path(list.id)
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to '/books'
  end

  private
  def list_params
    params.require(:list).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @list, url: update_book_path(@list.id), method: :patch do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Update Book' %>

<% end %>

<%= link_to "Show", book_path(@list.id) %> | <%= link_to "Back", "/books" %>

app/views/books/list.html.erb
<%= flash[:notice] %>


<p></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy", destroy_book_path(book.id), :method => :delete, "data-confirm" => "Are you sure?" %></td>
    <% end %>
    </tr>
  </tbody>
</table>

<h2>New book</h2>

<%= form_with model: @list, url: '/books', method: :post do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<%= flash[:notice] %>

<p>

  <strong>Title:</strong><%= @list.title %>

</p>

<p>

  <strong>Body:</strong><%= @list.body %>

</p>

<%= link_to "Edit", edit_book_path(@list.id) %> | <%= link_to "Back", "/books" %>

app/views/homes/index.html.erb
<h1>ようこそ<strong>Bookers</strong>へ</h1>

<p><strong>Bookers</strong>では、様々な書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><%= link_to "start", "/books" %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>